branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r ../buildbot/requirements.txt --use-mirrors
script:
- ../buildbot/build.sh 
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: W9jdJcVLMok2QnSWn94bkBZL6yiP88paWBSQvj5pNwx6rMA/KAuAmEDTmxWCRpvte9CP1mTpPgNRwn7UhhmZsw4f1AKEAClxNbpbVUhiISW+LoVmlkhw//fp+qGplhun2ID9sJpfjsgun5Ue4+dcpvI2rHP17lC5ZgJBj3fx85M=
before_install:
  - git clone --recursive https://github.com/openproceedings/openproceedings-buildbot.git ../buildbot
  - ln -s ../buildbot/content .
after_success: ../buildbot/deploy.sh 2013
